
[functions.send-event-notification]
enabled = true
verify_jwt = true
import_map = "./functions/send-event-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-event-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-event-notification/*.html" ]

[functions.send-assignment-notification]
enabled = true
verify_jwt = true
import_map = "./functions/send-assignment-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-assignment-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-assignment-notification/*.html" ]

[functions.notify-mentions]
enabled = true
verify_jwt = true
import_map = "./functions/notify-mentions/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notify-mentions/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notify-mentions/*.html" ]
